[build-system]
requires = ["setuptools >= 68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jigyasa_tree"
version = "0.1.0"
description = "A decision Tree builder for manual pruning, split suggestion and subtree refinement."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]

authors = [
	{name = "jaugustine"},
	]


dependencies = [
	"numpy >= 1.23,<1.25",
	"pandas >= 2.2,<2.4",
	"scikit-learn >= 1.2,<1.8",
	"matplotlib >= 3.6,<3.7",
	"joblib >= 1.2,<1.6"
]


keywords = [
	"decision-tree",
	"machine-learning",
	"classification",
	"scikit-learn",
	"tree-pruning",
	"explainable-ai"
]



classifiers = [
	"Programming Langauge :: python :: 3.11",
	"Programming Langauge :: python :: 3.12",
	"Programming Langauge :: python :: 3.13",
	"Programming Langauge :: python :: 3.14",
	"Operating System :: Os Independent",
	"Topic :: Scientific/Engineering :: Artificial Intelligene",
	"Topic :: Software Development",
]


[project.optional-dependencies] 
dev = [
	"pytest >= 9.0,<9.2",
	"build",
	"twine",
]


[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]


[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["test_*.py"]
python_funcions = ["test_*"]
addopts = "-v -ra --disable-warnings"

